version: '3'
services:
  db:
    image: postgres:14
    container_name: bwt-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: bwt-redis
    image: redis:6-alpine
    restart: always
    ports:
      - "${REDIS_PORT_EXTERNAL}:6379"

  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: bwt-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    ports:
      - "${MINIO_FIRST_PORT}:9000"
      - "${MINIO_SECOND_PORT}:9001"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bwt-app
    restart: always
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
      - redis
      - minio
    environment:
      NODE_ENV: development
      # Configuration DB
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # Configuration Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Configuration MinIO
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: 'false'
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

volumes:
  db_data:

networks:
  default:
    external: true
    name: bwt-net
