version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
