version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_NAME}"
  redis:
    image: redis
    ports:
      - "${REDIS_PORT_EXTERNAL}:6379"
    restart: always

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - "${APP_PORT}:3000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src
